trigger:

- none  #master



variables:

  # Agent VM image name

  vmImageName: 'ubuntu-latest'





stages:

- stage: Build

  displayName: Build stage

  jobs:

  - job: MavenPackageAndPublishArtifacts

    displayName: Maven Package and Publish Artifacts

    pool:

      vmImage: $(vmImageName)

      demands: maven

    

    steps:

    - task: Maven@4

      displayName: 'Maven Package'

      inputs:

        mavenPomFile: 'app/pom.xml'



    - task: CopyFiles@2

      displayName: 'Copy Files to artifact staging directory'

      inputs:

        SourceFolder: '$(System.DefaultWorkingDirectory)'

        Contents: '**/target/*.jar'

        TargetFolder: '$(Build.ArtifactStagingDirectory)'

      condition: succeededOrFailed()



    - task: PublishPipelineArtifact@0
      displayName: 'Publish pipeline artifacts'
      inputs:
        targetPath: $(Build.ArtifactStagingDirectory)


- stage: Deploy

  displayName: Deploy stage

  dependsOn: Build

  condition: succeeded()

  jobs:
  - deployment: DeployLinuxWebApp
    displayName: Deploy Linux Web App
    environment: 'development'
    pool: 
      vmImage: $(vmImageName)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@1
            displayName: 'Download Pipeline Artifact'
            inputs:
              buildType: 'current'
          - task: AzureRmWebAppDeployment@4

            displayName: 'Deploy Azure App Service'


            inputs:

              ConnectionType: 'AzureRM'

              azureSubscription: 'Azure subscription 1 (4f396e97-0b47-46ed-870f-d45e73eef667)'

              appType: 'webAppLinux'

              WebAppName: 'java-maven-app-erindi'

              packageForLinux: '$(System.ArtifactsDirectory)/drop/**/target/*.jar'